name: Madinah Cafe Radar

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # هذي السطور ضرورية عشان جيت هاب يقدر يحفظ الملفات
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run radar
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GMAPS_API_KEY: ${{ secrets.GMAPS_API_KEY }}
        run: python main.py

      - name: Save memory (Keep track of cafes)
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add last_places_ids.txt || echo "No changes"
          git commit -m "Update cafe memory" || echo "No changes"
          git push
