name: Madinah Radar System

on:
  schedule:
    # التغيير هنا: */20 تعني العمل كل 20 دقيقة
    - cron: '*/20 * * * *'
  workflow_dispatch: # يتيح لك تشغيله يدوياً في أي وقت

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests google-play-scraper
      - name: Run Radar
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
      - name: Save Memory
        run: |
          git config --global user.name "Talal Radar"
          git config --global user.email "radar@github.com"
          # حفظ ذاكرة التطبيقات والكافيهات لضمان عدم التكرار
          git add *.txt
          git commit -m "Update Radar Memory" || exit 0
          git push
